language: node_js
node_js: lts/*
deploy:
  provider: heroku
  api_key:
    secure: "XTneQBQXJi9j+7lzl9rlensCii9n5zx9zo36K3i00x6nK9jV/jS8zXWDtRTyN+D4b066/hrumPzluSquGIgVfcMSs3PFzdt5WY7icItTaJdYb+h4IK+lmmikKdoORpXxL0DwZkp+zYwfIKWTBDRHs9+AU267pXhklkpN59/vLzpz/B2czJAA5iUjrjTI8RpCUiDp7956rcbOAzWoB04nHfLPz3+VPA7GsunVVBuvOSzqgZRWVC5+sKOUaexWRWK0BTJagaCLVT3kSgFHZ7MqoW63X8GzEMdxh7BOGLBcN00Kdy2xLg0m9+nVeALSL6Bl+qcBcFaepjaTuLSR4wVW7rpyo9g9YqUU9Mf1bbyVoepZLIWJeHlU+9fhh5MBbKdmoR8vgYG3d+BYNZuiAfhCpcdd7NkennMqvJ652DjFPutTolBO4Gd0DlMVPR6rgv/yNc9/F2lhDttOvnC1MPD6JX11yA72TiawqY7jcoimWyzaOvh97vquAaVf5Pto3P4hgKtReUu9be87n26Tpql3hUExIBzTlIl7rRxrP+RneKyEpo6SsGeXelcgyZlKOc6ifwrKEXNhYMzFgxvFCx369MAQUcXOX+9BFjQ7fXwfQqCEXiJIMz5FR4OBtsX17ndPv2rtobhOpF0EOVB3Gc77crBEg3+F4ZKLoi7CGIvZxdY="
  app: bootcampbot
  on: master
